### PR TITLE
Using Microsoft Azure Computer Vision API to triage citizen science submissions

### PR DESCRIPTION
**Pull request by Fuhji**
Thank you for submitting a pull request for your new post. Please remember to assign the PR for review.

### Blog Post Title

Using AI to triage citizen science submissions

### Link to rendered version
https://fuhji.github.io/BritishGeologicalSurvey.github.io/front%20end/back%20end/autocaption/

### CODE REVIEW

**Comment by Fuhji** [comment]
@pdbebgs This post is ready for review when you are free

**Comment by pdbebgs** [comment]
You should teach me how to edit! In the meantime, there's a print out of a few small suggested changes on your desk. Let's talk about a better way if you're in on Friday.

A great article though

**Comment by Fuhji** [comment]
@pdbebgs fixes are in place now read for re-review

**Review by pdbebgs — APPROVED** [review]
Nice one Steve. Great article.

**Pull request closed without merging**
