### PR TITLE
Blog post on Rendertron and server side rendering

### PR DESCRIPTION
**Pull request by scientific-creative**
Post has been formatted, checked and is now ready for review + merge into BGS.

### CODE REVIEW

**Comment by Fuhji** [comment]
Please can you post a link to the rendered version of the post?

**Comment by scientific-creative** [comment]
https://scientific-creative.github.io/BGS/devops/seo/super-charging-seo-through-server-side-rendering/

Link to rendered article.

**Comment by scientific-creative** [comment]
I'm going to add a line or two about how this relates to UK GEOS. Should help when we post to twitter since we can also put on the UK GEOS twitter account. I'll issue an update and send a new post request ASAP.

**Comment by scientific-creative** [comment]
I'm going to add a line or two about how this relates to UK GEOS. Should help when we post to twitter since we can also put on the UK GEOS twitter account. I'll issue an update and send a new post request ASAP.

**Comment by scientific-creative** [comment]
I'm going to add a line or two about how this relates to UK GEOS. Should help when we post to twitter since we can also put on the UK GEOS twitter account. I'll issue an update and send a new post request ASAP.

**Comment by scientific-creative** [comment]
Tweaked and re-opened pull request for your review.

Full article on: https://scientific-creative.github.io/BGS/devops/seo/super-charging-seo-through-server-side-rendering/

@Fuhji @pdbebgs

**Comment by scientific-creative** [comment]
The following edits have been made:

+ Title changed to make it more specific toward "JavaScript" services
+ Typos fixed

**Pull request merged**
