### PR TITLE
Personas in product design

### PR DESCRIPTION
**Pull request by pautva**
### Description

Created a blog post about the use of personas in product design and added related images to the assets folder.

### Link to rendered version

* https://pautva.github.io/BritishGeologicalSurvey.github.io/ui-ux/personas/

### CODE REVIEW

**Comment by Fuhji** [comment]
@pdbebgs This blog post is ready for review. Please take a look at the URL and then click `add your review` where you can make suggested changes and/or approve:

image

**Comment by pdbebgs** [comment]
Hi, this reads great. Two small comments:

1. I think the link from user journeys to the design toolkit is internal? In which case it should be taken out
2. Can you confirm you have permission to publish the GC data discoverability personas? They were quite restrictive at the time, but may well now have given permission. Just checking.

Thanks

Patrick

**Comment by Fuhji** [comment]
@pautva are you happy to make the requested changes and let us know when ready to re-review?

**Comment by pautva** [comment]
I have just updated the internal links and sent a pull request. I'll check with Carl now if we can use the DD2 personas. If not, I will replace them with other personas.

**Comment by Fuhji** [comment]
> I have just updated the internal links and sent a pull request. I'll check with Carl now if we can use the DD2 personas. If not, I will replace them with other personas.

any update on DD2 personas being available publicly?

**Comment by pautva** [comment]
No, not yet. I might just go ahead and replace them with personas I created for Temporal Environmental Data 
Services (TEDS) project. They are ok to share.
https://bit.ly/3qxX3La

**Comment by Fuhji** [comment]
sounds a good plan - LGTM!

**Comment by pautva** [comment]
I replaced the personas and reworded the examples section. It's ready to go now.

**Comment by Fuhji** [comment]
Thanks @pautva ! @pdbebgs this is ready for final review and `merge pull request` once you are happy.

**Comment by pdbebgs** [comment]
Thanks Both - looks great. Merged.

**Pull request merged**
