### PR TITLE
Speeding up ETLHelper’s API transfers with asyncio

### PR DESCRIPTION
**Pull request by volcan01010**
Thank you for submitting a pull request for your new post. Please remember to assign the PR for review.

### Blog Post Title

Speeding up ETLHelper’s API transfers with asyncio

### Link to rendered version

https://volcan01010.github.io/BritishGeologicalSurvey.github.io/open-source/async-etlhelper-api-transfer/

### CODE REVIEW

**Comment by volcan01010** [comment]
@ximenesuk - I think this is pretty much ready.  It is worth you giving it a once-over to check the Python makes sense before it is formally submitted.  The snippets of code may not make sense out of the wider context, but I just wanted to highlight the main `asyncio` features.

Can you have a look when you get the chance, please?

**Comment by Fuhji** [comment]
bump @ximenesuk please can you pass on any comments for @volcan01010 ? 

@volcan01010 can you mark the MR as draft and remove WIP from the title so i'll know when to ping it for Patrick's review?

**Review by ximenesuk — APPROVED** [review]

**Comment by ximenesuk** [comment]
The post looks great. I've also converted to draft and removed 'WIP:' since there were no changes necessary.

**Comment by volcan01010** [comment]
Thanks @ximenesuk.  I've had another read through and made some minor tweaks.  I think that it is ready to go to Patrick now.

**Comment by Fuhji** [comment]
@pdbebgs This post is also ready for review

**Review by pdbebgs — COMMENTED** [review]
Really nice article. Only suggestion - I got a little confused between asyncio and aiohttp and how they were related. Maybe have another look and see if that needs a line of explanation. But happy if you decide that it's perfectly clear for the intended audience.

**Comment by volcan01010** [comment]
I added explicit description of `aiohttp` and `async` to the [asynchronous section](https://volcan01010.github.io/BritishGeologicalSurvey.github.io/open-source/async-etlhelper-api-transfer/#concurrent-posting-with-aiohttp-and-asyncio) to make it clearer.  I tweaked the wording in the intro and conclusion, too.

I'm happy that this is ready now.

**Review by pdbebgs — APPROVED** [review]
Looks great. Thanks John

**Pull request merged**
