### PR TITLE
added new post for 3d-geo-model-viewer

### PR DESCRIPTION
**Pull request by rachelheaven**
Thank you for submitting a pull request for your new post. Please remember to assign the PR for review.

### Blog Post Title

Web based 3D geological model viewer 

### Link to rendered version
Please include a link to the rendered version of your blog post so it can be seen its intended display format,

* https://rachelheaven.github.io/BritishGeologicalSurvey.github.io/visualisation/3d-model-viewer/

### CODE REVIEW

**Comment by Fuhji** [comment]
ready for your review @pdbebgs 👍

**Review by pdbebgs — APPROVED** [review]
This is great Rachel. Thank you. Couple of tiny things: 1. Just reread the 'Interactive web page' section. Think there's an extra 'in' within the sentence. 2. At the top of the document, there's a couple of instances of '3d' when the rest are '3D'.

**Comment by rachelheaven** [comment]
> This is great Rachel. Thank you. Couple of tiny things: 1. Just reread the 'Interactive web page' section. Think there's an extra 'in' within the sentence. 2. At the top of the document, there's a couple of instances of '3d' when the rest are '3D'.

Thanks Patrick - always good to have second pair of eyes ! Fixed in latest commit

**Comment by rachelheaven** [comment]
I've tweaked the content of the snippet of the mesh file data too. The actual data does have this ridiculously high precision, but it jars with the previous notes about saving file size by trimming unnecessary digits ! So I've rounded the numbers to 2 decimal places just for the purposes of this display.

**Review by pdbebgs — APPROVED** [review]

**Review by pdbebgs — APPROVED** [review]

**Review by pdbebgs — APPROVED** [review]

**Comment by pdbebgs** [comment]
All looks great to me now and ready to g. Nice one Rachel.

**Comment by Fuhji** [comment]
> All looks great to me now and ready to g. Nice one Rachel.

Time for the Big Green Button to make it live 👍

**Comment by pdbebgs** [comment]
Done!

**Pull request merged**
