### PR TITLE
Blog - Static Code Analysis with SonaQube

### PR DESCRIPTION
**Pull request by atkinspa33**
Thank you for submitting a pull request for your new post. Please remember to assign the PR for review.

### Blog Post Title

Static Code Analysis with SonarQube

### Link to rendered version
Please include a link to the rendered version of your blog post so it can be seen its intended display format,

* https://atkinspa33.github.io/BritishGeologicalSurvey.github.io/software%20development/static-code-analysis/

### CODE REVIEW

**Comment by Fuhji** [comment]
@pdbebgs This is the next in line for review when ready

**Review by pdbebgs — APPROVED** [review]
Really nice blog Phil. Can you think of a forum to promote use of this tool amongst developers. I've got it on my list of possible future 'show and tell' sessions, but you might have a better idea to promote its wider use?

**Comment by Fuhji** [comment]
Thanks @pdbebgs I will hold back releasing this blog until December,  by which time we will have more info on promotional activities available for each new post.

**Comment by atkinspa33** [comment]
> Really nice blog Phil. Can you think of a forum to promote use of this tool amongst developers. I've got it on my list of possible future 'show and tell' sessions, but you might have a better idea to promote its wider use?

I think a show and tell session would be an ideal forum. The Java devs are all proably aware of SonarQube now, and we have a GitLab wiki guide orientated towards it's use with Java projects. I had planned to also trial it with a Python project (the new Geosemantics OCR tool) and add a Python section to the wiki. When I get a bit of time I'll give it a go and see if Colin Blackburn would be happy to review and discuss it's use in CI pipelines.

**Comment by Fuhji** [comment]
I would be interested in knowing more about integrating SonarQube into the JavaScript/npm world as well. I think that EPOS may already have done this, although with Jon leaving some of the knowledge may have left with him.

**Comment by pdbebgs** [comment]
Great thanks Phil. When you're ready to do a show and tell, give me a shout and we'll get a date in the calendar.

**Comment by atkinspa33** [comment]
> I would be interested in knowing more about integrating SonarQube into the JavaScript/npm world as well. I think that EPOS may already have done this, although with Jon leaving some of the knowledge may have left with him.

I remember Jon did have a SonarQube IDE plugin (possibly VS Code) installed and working. However, the SonarQube scans on the EPOS components are not being run as part of the CI pipelines. The last scans appear to be 10-12 months old and only run against the main branch, which probably highlights the need for them to be automated. For one of our BGS Java projects we used SonarQube's Maven support to run it as part of the CI pipeline. Hopefully, similar support will be available for the build tools of our JavaScript and Python projects. I'll keep JavaScript in mind when revisiting the documentation.

**Pull request merged**
